### ISSUE TITLE
关于文章发表事宜

### ISSUE THREAD

**Issue by beyoung** [CDUT-GIS/Algorithm#1]
此次讨论发表文章原因有三：
* 研究生毕业有文章要求；
* 涉及到研究生期间奖学金评定；
* 增加团队的技能。

预期发表文章内容包括：
* 机器学习相关算法运用在滑坡危险性评价之上（Adaboost算法，深度学习算法，SVM等）；
* 机器学习相关算法运用在油气存储评价之上（Adaboost算法，深度学习算法，SVM等）；

具体实施：
* 机器学习相关算法运用在滑坡危险性评价之上主要由@beyoung负责
* 机器学习相关算法运用在油气存储评价之上主要由@King-JXN负责

预期完成时间：
初步估计在四月中旬完成实验相关内容 ，五月初完成初稿。

**Comment by PsArvin** [comment]
我需要准备些什么吗？阅读一些文献、了解算法之类？

**Comment by beyoung** [comment]
你和@King-JXN负责深度学习算法实验，我和龙儿负责Adaboost算法的实验。

**Comment by PsArvin** [comment]
目标明确了，突然之间充满了激情呢~
